### ISSUE TITLE
delegatecheck - No such command

### ISSUE THREAD

**Issue by leebaird** [sensepost/thumbscr-ews#3]
Kali Linux 2020.4 rolling, completely patched.

└─# python3 --version
Python 3.9.1+

└─# python3 thumbscr-ews.py -C test.yml --exch-host webmail.acme.com/ews/exchange.asmx delegatecheck
Usage: thumbscr-ews.py [OPTIONS] COMMAND [ARGS]...
Try 'thumbscr-ews.py --help' for help.

Error: No such command 'delegatecheck'.

**Comment by Cablethief** [comment]
I think I accidentally replaced one too many things, I have fixed this now.
